detectors:
  IrresponsibleModule:
    enabled: false

directories:
  'db/migrate':
    UncommunicativeVariableName:
      enabled: false
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
