detectors:
  DuplicateMethodCall:
    allow_calls:
      - 'format.html'
      - 'format.json'
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    max_statements: 10

directories:
  'db/migrate':
    UncommunicativeVariableName:
      enabled: false
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
  'app/controllers':
    InstanceVariableAssumption:
      enabled: false
