# Set global options and exlude auto-managed files
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/*'

# Better paramter alignment
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Be a bit more linent on line length limits and ignore comments
Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\A\s*#']

# Allow longer blocks/methods in database migrations and rspecs
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
    - 'config/Guardfile'

Style/ClassAndModuleChildren:
  Enabled: false
# Ignore class documentation except in models
Style/Documentation:
  Exclude:
    - 'app/controllers/*_controller.rb'
    - 'app/helpers/*_helper.rb'
    - 'app/mailers/*_mailer.rb'
    - 'app/models/application_record.rb'
    - 'db/migrate/**/*'
    - 'config/application.rb'
    - 'spec/**/*'
    - 'test/**/*'

# Use explicit symbol arrays
Style/SymbolArray:
  EnforcedStyle: brackets

# Don't require frozen string literals
Style/FrozenStringLiteralComment:
    Enabled: false
